# Generated by Django 6.0.1 on 2026-07-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_tags',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
