# Generated by Django 6.0.1 on 2026-07-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_socialconnect'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconnect',
            name='whatsapp_access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='socialconnect',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
