# Generated by Django 6.0.1 on 2026-08-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_socialconnect_whatsapp_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email_preview_text',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_sender_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_subject',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='recipient',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email Broadcast')], default='WHATSAPP', max_length=20),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
