"""
Django settings for smartbiz_backend project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
import os
from dotenv import load_dotenv
import dj_database_url

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'users',
    'brand',
    'billing',
    'content',
    'business',
    'marketplace',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smartbiz_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'dist'], # Path inside container/backend folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartbiz_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(default='sqlite:///db.sqlite3', conn_max_age=600)
}

# Set a strict 3-second connection timeout to prevent database connection hangs during startup (only for non-SQLite databases)
if 'OPTIONS' not in DATABASES['default']:
    DATABASES['default']['OPTIONS'] = {}
if 'sqlite' not in DATABASES['default'].get('ENGINE', ''):
    DATABASES['default']['OPTIONS']['connect_timeout'] = 3




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS/CSRF Settings
CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:5173,http://localhost:3000,https://*.railway.app,https://smartbizcoach.com.ng,https://www.smartbizcoach.com.ng,https://api.smartbizcoach.com.ng').split(',')
    if origin.strip()
]


CSRF_COOKIE_SAMESITE = 'Lax' if DEBUG else 'None'
CSRF_COOKIE_SECURE = not DEBUG

AUTH_USER_MODEL = 'users.User'

# Static files (WhiteNoise)
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.WhiteNoiseStaticFilesStorage'

# Look for frontend build in 'dist' directory
FRONTEND_DIST_DIR = BASE_DIR / 'dist'
STATICFILES_DIRS = []
if FRONTEND_DIST_DIR.exists():
    STATICFILES_DIRS.append(str(FRONTEND_DIST_DIR))
    print(f"Found frontend assets at {FRONTEND_DIST_DIR}")
else:
    # During container build, it might be here
    ALT_DIST = Path('/dist')
    if ALT_DIST.exists():
        STATICFILES_DIRS.append(str(ALT_DIST))
        print(f"Found frontend assets at {ALT_DIST}")
    else:
        print(f"Warning: Frontend assets not found")


if not DEBUG:
    # NOTE: Do NOT set SECURE_SSL_REDIRECT = True on Railway.
    # Railway's edge proxy already terminates SSL and forwards HTTP internally.
    # Setting this causes an infinite redirect loop → 502 Bad Gateway.
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    X_FRAME_OPTIONS = 'DENY'

# Validate critical environment variables
import sys
if not os.environ.get('GEMINI_API_KEY'):
    print("WARNING: No GEMINI_API_KEY set. AI features will not work.")

if not os.environ.get('SECRET_KEY') or 'django-insecure' in os.environ.get('SECRET_KEY', ''):
    print("WARNING: Using insecure SECRET_KEY")

# Paystack Configuration
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY')

# Squad Configuration
SQUAD_SECRET_KEY = os.getenv('SQUAD_SECRET_KEY')

# ─── Email Configuration (Brevo / Sendinblue SMTP) ───────────────────────────
# Provider: Brevo (https://app.brevo.com → SMTP & API)
# Set these in Railway env vars:
#   EMAIL_HOST          = smtp-relay.brevo.com
#   EMAIL_PORT          = 587
#   EMAIL_HOST_USER     = aa3358001@smtp-brevo.com   (your Brevo SMTP login)
#   EMAIL_HOST_PASSWORD = <your Brevo SMTP key>      (the key ending in YoqCCw)
#   DEFAULT_FROM_EMAIL  = noreply@smartbizcoach.com.ng  (a verified Brevo sender)
#
# ⚠  Brevo blocks SMTP keys by IP by default.
#    Go to Brevo → Settings → SMTP & API → Authorized IPs and add Railway's IP,
#    OR set the SMTP key to "Allow all IPs" in the Brevo dashboard.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp-relay.brevo.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@smartbizcoach.com.ng')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Fall back to console if no email credentials set (useful for dev)
if not EMAIL_HOST_USER:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ─── DRF Throttling (Rate Limiting) ──────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '200/day',       # Global: 200 requests/user/day
        'brand_gen': '5/hour',   # Brand generation
        'content_gen': '20/hour',# Content generation
        'business_plan': '3/day',# Business plan
        'video_gen': '5/day',    # Video script generation
        'image_edit': '10/day',  # Image editing
    }
}

# ─── Sentry Error Tracking ────────────────────────────────────────────────────
SENTRY_DSN = os.getenv('SENTRY_DSN', '')  # Set SENTRY_DSN in Railway env vars
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=0.1,   # 10% of requests for performance tracing
        send_default_pii=False,   # Don't send personal data to Sentry
        environment="production" if not DEBUG else "development",
    )
