# Generated by Django 6.0.1 on 2026-05-07 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_brandidentity_slug'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_contact', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('lead_type', models.CharField(choices=[('ORDER', 'Direct Order'), ('INQUIRY', 'Service/Property Inquiry'), ('B2B', 'Wholesale Inquiry')], default='INQUIRY', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New Inquiry'), ('FOLLOW_UP', 'Following Up'), ('NEGOTIATING', 'Negotiating'), ('WON', 'Completed/Won'), ('LOST', 'Lost/Cancelled')], default='NEW', max_length=20)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='brand.brandidentity')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.product')),
            ],
        ),
    ]
