# Generated by Django 6.0.1 on 2026-07-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
