# Generated by Django 6.0.1 on 2026-08-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_vendorverification_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promoted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
