# Generated by Django 6.0.1 on 2026-10-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_dailyexpense_dailysale'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexpense',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyexpense',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailysale',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysale',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
