# Generated by Django 6.0.1 on 2026-07-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_agenthirerequest_usercompliance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credits',
            field=models.IntegerField(default=500),
        ),
    ]
