# Generated by Django 6.0.1 on 2026-08-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
