# Generated by Django 6.0.1 on 2026-08-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenthirerequest',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='agenthirerequest',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='agenthirerequest',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid / In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='agenthirerequest',
            name='registration_type',
            field=models.CharField(blank=True, default='Business Name', max_length=100),
        ),
    ]
