# Generated by Django 6.0.1 on 2026-10-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_enable_supabase_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('organization', models.CharField(max_length=255)),
                ('partnership_type', models.CharField(choices=[('SME Training & NGO Cohorts', 'SME Training & NGO Cohorts'), ('Bank / Microfinance Credit Scoring', 'Bank / Microfinance Credit Scoring'), ('Government Agency (SMEDAN, BOI)', 'Government Agency (SMEDAN, BOI)'), ('Market Association / Cooperative', 'Market Association / Cooperative'), ('Equity Investment / Venture Capital', 'Equity Investment / Venture Capital'), ('Other', 'Other Strategic Partnership')], default='SME Training & NGO Cohorts', max_length=100)),
                ('cohort_size', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.TextField()),
                ('source', models.CharField(default='Landing Page', max_length=100)),
                ('status', models.CharField(choices=[('NEW', 'New Inquiry'), ('IN_REVIEW', 'In Review'), ('CONTACTED', 'Contacted / Meeting Scheduled'), ('PILOT_ACTIVE', 'Pilot Active'), ('DECLINED', 'Declined / Closed')], default='NEW', max_length=50)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partnership & Cohort Inquiry',
                'verbose_name_plural': 'Partnership & Cohort Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
