# Generated by Django 6.0 on 2025-12-09 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('niche', models.CharField(max_length=100)),
                ('vibe', models.CharField(max_length=100)),
                ('colors', models.JSONField(default=dict)),
                ('fonts', models.JSONField(default=dict)),
                ('taglines', models.JSONField(default=list)),
                ('social_bio', models.TextField(blank=True)),
                ('whatsapp_greeting', models.TextField(blank=True)),
                ('elevator_pitch', models.TextField(blank=True)),
                ('brand_voice', models.CharField(blank=True, max_length=100)),
                ('target_audience', models.TextField(blank=True)),
                ('logo_prompt', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('policies', models.JSONField(default=dict)),
                ('trust_badge_text', models.CharField(blank=True, max_length=255)),
                ('whatsapp_content', models.JSONField(default=dict)),
                ('packaging', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('POST', 'Post'), ('SCRIPT', 'Script'), ('PLAN', 'Plan')], max_length=20)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.JSONField(default=list)),
                ('call_to_action', models.CharField(blank=True, max_length=255)),
                ('slides', models.JSONField(default=list)),
                ('image_text', models.CharField(blank=True, max_length=255)),
                ('dm_reply', models.TextField(blank=True)),
                ('script', models.JSONField(blank=True, default=dict)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('niche', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_content', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
