# Generated by Django 6.0.1 on 2026-07-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_brandidentity_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandidentity',
            name='logo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandidentity',
            name='niche',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='brandidentity',
            name='vibe',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
