# Generated by Django 6.0.1 on 2026-08-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_alter_brandidentity_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandidentity',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
