# Generated by Django 6.0.1 on 2026-10-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_brandidentity_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandidentity',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='cac_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='core_values',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='corporate_entity_type',
            field=models.CharField(blank=True, default='Registered Business Name (BN)', max_length=50),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='executive_bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='mission',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='ndpr_compliance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='sla_policy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='smedan_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='tin_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='brandidentity',
            name='vision',
            field=models.TextField(blank=True, default=''),
        ),
    ]
